name: privilege

description: A new Flutter application.

publish_to: 'none'

version: 3.0.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  chewie: ^1.3.2
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_html: ^3.0.0-alpha.3
  image_picker: ^0.8.5+3
  flutter_launch: ^0.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_offline: ^2.1.0
  webview_flutter:
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_verification_code: ^1.1.2+1
  flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.0.9
  hexcolor: ^2.0.2
  http: ^0.13.4
  intl: ^0.17.0
  otp_text_field: ^1.1.2
  shared_preferences: ^2.0.8
  splash_screen_view: ^3.0.0
  syncfusion_flutter_pdfviewer: ^19.2.44-beta
  url_launcher: ^6.0.7
  video_player: ^2.4.5
  whatsapp_unilink: ^2.0.1+1
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2
  flutter_inappwebview: ^5.4.3+7
  firebase_messaging: ^12.0.1
  firebase_core: ^1.20.0
  syncfusion_flutter_calendar: ^19.1.59
  table_calendar: ^3.0.6
  google_fonts: ^3.0.1
  sqflite:
  provider:


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
